---
all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: /usr/bin/python3
    winhost:
      ansible_connection: ssh
      ansible_shell_type: powershell
  children:
    wsl:
      hosts: 
        localhost:
    windows:
      hosts:
        winhost:
